export default {
  aboutUs: '/about-us',
  ai: '/ai',
  aiGateway: '/site-audit',
  siteAudit: '/site-audit',
  lakebase: '/ai-visibility',
  blog: '/blog',
  branching: '/branching',
  brand: '/brand',
  careers:
    'https://www.databricks.com/company/careers/open-positions?department=engineering&location=all&itm_source=www&itm_category=company&itm_page=engineering-at-databricks&itm_location=body&itm_component=hero&itm_offer=open-positions',
  caseStudies: '/case-studies',
  claimableNeon: '/claimable-neon',
  cli: '/mcp',
  mcp: '/mcp',
  appMcpSettings: 'https://app.ranksmile.pl/settings/api',
  contactSales: '/contact-sales',
  enterprise: '/agencies',
  agencies: '/agencies',
  flow: '/flow',
  functions: '/rank-tracking',
  faster: '/faster',
  guides: '/guides',
  faqs: '/faqs',
  generateTicket: '/generate-ticket',
  migration: '/migration',
  objectStorage: '/wordpress',
  partners: '/docs/guides/platform-integration-overview',
  postgresqltutorial: '/postgresql/tutorial',
  pricing: '/pricing',
  programs: '/programs',
  programsAgents: '/programs/agents',
  scaleTrial: '/scale-trial',
  security: '/security',
  startups: '/startups',
  storage: '/storage',
  subprocessorsSubscribe: '/subscribe-to-subprocessors',
  platforms: '/platforms',
  useCases: '/use-cases',
  useCasesAI: '/use-cases/ai-agents',
  autoscalingReport: '/autoscaling-report',
  tools: '/tools',
  toolsUpgradeAssessment: '/tools/postgres-major-version-assessment/assess',
  toolsMigration: '/tools/postgres-migration',

  // Ranksmile product pages (Neon routes kept, content repurposed)
  aiVisibility: '/ai-visibility',
  contentScore: '/content-score',
  rankTracking: '/rank-tracking',
  keywordResearch: '/site-audit',
  wordpress: '/wordpress',
  mcpApi: '/mcp',
  contact: 'mailto:kontakt@ranksmile.pl',
  legalTerms: 'https://app.ranksmile.pl/legal/terms',
  legalPrivacy: 'https://app.ranksmile.pl/legal/privacy',
  legalCookies: 'https://app.ranksmile.pl/legal/cookies',
  legalDpa: 'https://app.ranksmile.pl/legal/dpa',
  legalHub: 'https://app.ranksmile.pl/legal',
  appBilling: 'https://app.ranksmile.pl/billing',

  // Docs
  docs: '/docs',
  docsHome: '/docs/introduction',
  api: '/docs/reference/api',
  architecture: '/docs/introduction/architecture-overview',
  postgresOverview: '/docs/postgres/overview',
  auth: '/docs/neon-auth/overview',
  authOverview: '/docs/auth/overview',
  authPage: '/content-score',
  functionsOverview: '/docs/compute/functions/overview',
  objectStorageOverview: '/docs/storage/overview',
  aiGatewayOverview: '/docs/ai-gateway/overview',
  aiGatewayGetStarted: '/docs/ai-gateway/get-started',
  autoscaling: '/docs/introduction/autoscaling',
  billing: '/docs/introduction/about-billing',
  branchRestore: '/docs/introduction/branch-restore',
  changelog: '/docs/changelog',
  cliInstall: '/docs/cli/install',
  cliReference: '/docs/cli',
  connectionPooling: '/docs/connect/connection-pooling',
  communityIntro: '/docs/community/community-intro',
  dataApi: '/docs/data-api/get-started',
  docsAi: '/docs/ai/ai-intro',
  docsBranching: '/docs/introduction/branching',
  docsHighAvailability: '/docs/introduction/high-availability',
  docsMigration: '/docs/import/import-data-assistant',
  docsPgvector: '/docs/extensions/pgvector',
  instantRestore: '/docs/introduction/branch-restore',
  lakebaseSearch: '/docs/ai/lakebase-search',
  manageBilling: '/docs/introduction/manage-billing',
  migrationIntro: '/docs/import/migrate-intro',
  docsExtensionsPgVector: '/docs/extensions/pgvector',
  docsExtensionsPostgisRelatedExtensions: '/docs/extensions/postgis-related-extensions',
  docsExtensionsTimescaledb: '/docs/extensions/timescaledb',
  readReplicas: '/docs/introduction/read-replicas',
  serverless: '/docs/introduction/serverless',
  support: 'mailto:kontakt@ranksmile.pl',
  scaleToZero: '/docs/guides/scale-to-zero-guide',
  whyNeon: '/docs/get-started/why-neon',

  // Legal
  dpa: '/platform-terms#3.4',
  websiteTerms: 'https://www.databricks.com/legal/terms-of-use',
  platformTerms: '/platform-terms',
  privacy: 'https://www.databricks.com/legal/privacynotice',
  privacyPolicy: 'https://www.databricks.com/legal/privacynotice',
  modernSlaveryStatement: 'https://www.databricks.com/legal/modern-slavery-policy-statement',
  californiaPolicy:
    'https://www.databricks.com/legal/supplemental-privacy-notice-california-residents',
  cookiePolicy: '/cookie-policy',
  subprocessors: 'https://www.databricks.com/legal/databricks-subprocessors',
  businessInformation: '/business-info',
  hipaaCompliance: '/docs/security/hipaa',
  hipaaContractors: '/hipaa-contractors',

  // Console
  console: 'https://app.ranksmile.pl',
  login: 'https://app.ranksmile.pl/auth/sign-in',
  signup: 'https://app.ranksmile.pl/auth/sign-up',
  signupCredits: 'https://fyi.neon.tech/credits',
  consoleSupport: 'mailto:kontakt@ranksmile.pl',

  // Socials
  discord: 'https://neon.com/discord',
  github: 'https://github.com/neondatabase',
  linkedin: 'https://www.linkedin.com/company/neondatabase/',
  twitter: 'https://x.com/neondatabase',
  youtube: 'https://www.youtube.com/channel/UCoMzQTJSIr7-RU1QbomQI2w',

  // Copilot
  githubCopilot: 'https://github.com/marketplace/neon-database',
  discordCopilot: 'https://discord.com/channels/1176467419317940276/1222626436502782013',
  vscodeCopilot:
    'https://marketplace.visualstudio.com/items?itemName=buildwithlayer.neon-integration-expert-15j6N',

  // Compliance
  trust: 'https://trust.neon.com',
  certCCPA: 'https://trust.neon.com/?itemUid=4064ac33-7b48-407b-aed7-ce02971d1ec1',
  certGDPR: 'https://trust.neon.com/?itemUid=45220873-6e51-4dbb-b1b1-37d66ee9ef95',
  certISO27001: 'https://trust.neon.com/?itemUid=1fed9faa-4a87-427c-9a95-96b4d6bf66b7',
  certISO27701: 'https://trust.neon.com/?itemUid=dc79cbc7-c99d-4eb9-891e-f5dc44b943d7',
  certSOC2: 'https://trust.neon.com/?itemUid=7bfa66da-33ab-49de-8391-e329738a1ae9',
  certHIPAA: '/docs/security/hipaa',

  // Other
  status: 'https://neonstatus.com',
  cdn: 'https://cdn.neonapi.io',
  apiReference: '/docs/reference/api',
  bugBounty: 'https://hackerone.com/neon_bbp',
  bookMeeting: 'https://calendly.com/d/cm8j-8yw-fq8',
};
